# Generated by Django 4.2.13 on 2024-06-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_customer_staff_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Sold',
            field=models.IntegerField(default=0),
        ),
    ]
